import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { expectHydrated } from '../support/hydration'

async function login(page: Page) {
  await page.goto('/admin/login')
  await expectHydrated(page)
  await page.getByTestId('username').fill('gavin')
  await page.getByTestId('password').fill('correct-horse')
  await page.getByTestId('login').click()
  await expect(page).toHaveURL(/\/admin\/articles$/)
}

test('password form verifies errors confirmation and success', async ({ page }) => {
  await login(page)
  await page.route('**/api/v1/auth/account', route => route.fulfill({ json: { username: 'gavin', email_masked: 'g***@163.com', mail_available: true } }))
  await page.goto('/admin/account')
  await page.getByLabel('当前密码', { exact: true }).fill('correct-horse')
  await page.route('**/api/v1/auth/account/code', route => route.fulfill({ status: 503, json: { detail: 'mail_unavailable' } }))
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('邮件暂不可用')
  await expect(page.getByRole('button', { name: '修改密码', exact: true })).toBeDisabled()
  await page.unroute('**/api/v1/auth/account/code')
  await page.route('**/api/v1/auth/account/code', route => route.fulfill({ status: 202, json: { challenge_id: 'test-only-challenge', expires_in: 600, retry_after: 60 } }))
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '已提交发送' })).toBeVisible()
  await expect(page.getByRole('button', { name: /秒后重发/ })).toBeDisabled()
  await page.getByLabel('新密码', { exact: true }).fill('a-test-password-2026')
  await page.getByLabel('确认新密码', { exact: true }).fill('a-different-password')
  await page.getByLabel('邮箱验证码').fill('123456')
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('两次新密码输入不一致。')
  await page.getByLabel('确认新密码', { exact: true }).fill('a-test-password-2026')
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.route('**/api/v1/auth/account/password', route => route.fulfill({ status: 400, json: { detail: 'invalid_code' } }))
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  await page.getByRole('button', { name: '确认更新密码', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('验证码错误')
  await expect(page.getByLabel('新密码', { exact: true })).toHaveValue('a-test-password-2026')
  await page.unroute('**/api/v1/auth/account/password')
  await page.route('**/api/v1/auth/account/password', async (route) => {
    expect(route.request().postDataJSON()).toEqual({ current_password: 'correct-horse', new_password: 'a-test-password-2026', challenge_id: 'test-only-challenge', code: '123456' })
    await route.fulfill({ status: 204 })
  })
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  await page.getByRole('button', { name: '确认更新密码', exact: true }).click()
  await expect(page).toHaveURL(/reason=password-updated/)
  await expect(page.getByTestId('password')).toHaveValue('')
})

test('account information and navigation', async ({ page }) => {
  await login(page)
  await page.getByRole('link', { name: '账号安全', exact: true }).click()
  await expect(page.getByTestId('account-username')).toHaveText('gavin')
  await expect(page.getByTestId('account-email')).toHaveText('尚未配置')
  await expect(page.getByRole('link', { name: '账号安全', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.setViewportSize({ width: 320, height: 800 })
  await page.getByTestId('admin-menu-toggle').click()
  await expect(page.getByRole('link', { name: '账号安全', exact: true }).filter({ visible: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.route('**/api/v1/auth/account', route => route.fulfill({ status: 503, json: { detail: 'unavailable' } }))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('账号信息读取失败')
  await page.unroute('**/api/v1/auth/account')
  await page.getByRole('button', { name: '重新读取', exact: true }).click()
  await expect(page.getByTestId('account-username')).toHaveText('gavin')
  await page.route('**/api/v1/auth/account', route => route.fulfill({ status: 401, json: { detail: 'unauthorized' } }))
  await page.reload()
  await expect(page).toHaveURL(/\/admin\/login\?reason=session-expired$/)
})

test('recovery entry csrf and reset feedback', async ({ page }) => {
  await page.goto('/admin/login')
  await expectHydrated(page)
  await page.getByRole('link', { name: '忘记密码', exact: true }).click()
  await expect(page.getByRole('heading', { name: '找回密码' })).toBeVisible()
  await expect(page.getByLabel('当前密码', { exact: true })).toHaveCount(0)
  await expect(page.locator('input[type=email]')).toHaveCount(0)
  await page.route('**/api/v1/auth/recovery/code', async (route) => {
    expect(route.request().headers()['x-csrf-token']).toBeTruthy()
    expect(route.request().postDataJSON()).toEqual({})
    await route.fulfill({ status: 202, json: { challenge_id: 'recovery-test', expires_in: 600, retry_after: 60 } })
  })
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('已提交发送')
  await page.getByLabel('新密码', { exact: true }).fill('recovered-password-2026')
  await page.getByLabel('确认新密码', { exact: true }).fill('recovered-password-2026')
  await page.getByLabel('邮箱验证码').fill('123456')
  await page.route('**/api/v1/auth/recovery/password', async (route) => {
    expect(route.request().headers()['x-csrf-token']).toBeTruthy()
    expect(route.request().postDataJSON()).toEqual({ new_password: 'recovered-password-2026', challenge_id: 'recovery-test', code: '123456' })
    await route.fulfill({ status: 204 })
  })
  await page.getByRole('button', { name: '重设密码', exact: true }).click()
  await page.getByRole('button', { name: '确认更新密码', exact: true }).click()
  await expect(page).toHaveURL(/password-updated/)
  await expect(page.getByRole('status')).toContainText('请使用新密码登录')
  await expect(page.getByTestId('password')).toHaveValue('')
})

test('sessions revoke selected others and current with real API', async ({ page, browser }) => {
  const other = await browser.newContext()
  const third = await browser.newContext()
  try {
    const otherPage = await other.newPage()
    const thirdPage = await third.newPage()
    await login(page)
    await login(otherPage)
    await login(thirdPage)
    const target = (await (await other.request.get('http://127.0.0.1:3100/api/v1/auth/sessions')).json()).items.find((item: { is_current: boolean }) => item.is_current)
    await page.goto('/admin/account')
    await expect(page.getByTestId('current-session')).toHaveCount(1)
    await expect(page.getByTestId('current-session').locator('time')).toHaveCount(2)
    const others = page.getByTestId('other-session')
    const response = await page.request.get('/api/v1/auth/sessions')
    const list = (await response.json()).items
    const index = list.filter((item: { is_current: boolean }) => !item.is_current).findIndex((item: { id: string }) => item.id === target.id)
    await others.nth(index).getByRole('button').click()
    await page.getByRole('button', { name: '确认退出', exact: true }).click()
    await expect(page.getByRole('status').filter({ hasText: '所选会话已退出' })).toBeVisible()
    expect((await other.request.get('http://127.0.0.1:3100/api/v1/auth/session')).status()).toBe(401)
    expect((await third.request.get('http://127.0.0.1:3100/api/v1/auth/session')).status()).toBe(200)
    await page.getByRole('button', { name: '退出其他会话', exact: true }).click()
    await page.getByRole('button', { name: '确认退出', exact: true }).click()
    await expect(page.getByTestId('other-session')).toHaveCount(0)
    expect((await third.request.get('http://127.0.0.1:3100/api/v1/auth/session')).status()).toBe(401)
    expect((await page.request.get('/api/v1/auth/session')).status()).toBe(200)
    await page.getByRole('button', { name: '退出当前会话', exact: true }).click()
    await page.getByRole('button', { name: '确认退出', exact: true }).click()
    await expect(page).toHaveURL(/reason=session-revoked/)
    expect((await page.request.get('/api/v1/auth/session')).status()).toBe(401)
  }
  finally { await other.close(); await third.close() }
})

test('account pages themes responsive keyboard and failure states', async ({ page }, info) => {
  await login(page)
  await page.route('**/api/v1/auth/account', route => route.fulfill({ json: { username: 'gavin', email_masked: 'g***@163.com', mail_available: true } }))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  for (const path of ['/admin/account', '/admin/recover', '/admin/login']) {
    await page.goto(path)
    await expectHydrated(page)
    for (const dark of [false, true]) {
      if (await page.locator('html').evaluate(el => el.classList.contains('dark')) !== dark) await page.getByRole('button', { name: '切换颜色主题' }).filter({ visible: true }).click()
      await expect.poll(() => page.locator('html').evaluate(el => el.classList.contains('dark'))).toBe(dark)
      for (const width of [1440, 1280, 1024, 768, 390, 320]) {
        await page.setViewportSize({ width, height: 1000 })
        await expect(page.locator('h1')).toBeVisible()
        expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth), `${path} ${dark} ${width}`).toBeLessThanOrEqual(1)
      }
      await expect.poll(() => page.evaluate(() => document.getAnimations().filter(animation => animation instanceof CSSTransition && animation.playState === 'running').length)).toBe(0)
      const result = await new AxeBuilder({ page }).include(path === '/admin/account' ? '#admin-main' : 'main').withTags(['wcag2a', 'wcag2aa']).analyze()
      expect(result.violations).toEqual([])
      await page.screenshot({ path: info.outputPath(`${path.split('/').pop()}-${dark ? 'dark' : 'light'}-320.png`), fullPage: true })
      await page.setViewportSize({ width: 1440, height: 1000 })
      await page.screenshot({ path: info.outputPath(`${path.split('/').pop()}-${dark ? 'dark' : 'light'}-1440.png`), fullPage: true })
    }
  }
  await page.goto('/admin/account')
  await page.route('**/api/v1/auth/sessions', route => route.fulfill({ status: 503, json: { detail: 'unavailable' } }))
  await page.getByRole('button', { name: '刷新会话' }).click()
  await expect(page.getByRole('alert')).toContainText('操作未确认成功')
  await expect(page.getByText('没有活跃会话。')).toHaveCount(0)
  await page.unroute('**/api/v1/auth/sessions')
  await page.getByRole('button', { name: '刷新会话' }).click()
  await expect(page.getByTestId('current-session')).toBeVisible()
  await page.getByRole('button', { name: '退出当前会话', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: '取消', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: '确认退出', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '退出当前会话', exact: true })).toBeFocused()
  await page.getByLabel('当前密码', { exact: true }).fill('correct-horse')
  await page.route('**/api/v1/auth/account/code', route => route.fulfill({ status: 403, json: { detail: 'forbidden' } }))
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('安全校验失败')
  await page.unroute('**/api/v1/auth/account/code')
  await page.route('**/api/v1/auth/account/code', route => route.fulfill({ status: 429, headers: { 'Retry-After': '2' }, json: { detail: 'rate_limited' } }))
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('2 秒后重试')
  await expect(page.getByRole('button', { name: /秒后重发/ })).toBeDisabled()
  await page.unroute('**/api/v1/auth/account/code')
  await page.route('**/api/v1/auth/account/code', route => route.fulfill({ status: 401, json: { detail: 'unauthorized' } }))
  await page.getByRole('button', { name: '发送验证码', exact: true }).click()
  await expect(page).toHaveURL(/session-expired/)
  await expect(page.getByTestId('password')).toHaveValue('')
  expect(errors).toEqual([])
})
