import { join } from 'node:path'
import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
import { expectHydrated } from '../support/hydration'

const open = async (page: Page, path: string) => { await page.goto(path); await expectHydrated(page) }
const login = async (page: Page) => {
  await open(page, '/admin/login')
  await page.getByTestId('username').fill('gavin')
  await page.getByTestId('password').fill('correct-horse')
  await page.getByTestId('login').click()
  await expect(page).toHaveURL(/\/admin\/articles$/)
  return { 'X-CSRF-Token': (await page.context().cookies()).find(c => c.name === 'gavin_csrf')!.value }
}
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')
const fail = async (page: Page, pattern: string, method: string) => page.route(pattern, route =>
  route.request().method() === method ? route.fulfill({ status: 503, json: { detail: '隔离故障' } }) : route.continue())

test('ops layout', async ({ page }, info) => {
  test.setTimeout(360_000)
  const headers = await login(page)
  const response = await page.request.post('/api/v1/admin/categories', { headers, data: { name: '审查栏目'.repeat(12), slug: 'layout-long-category', description: '隔离长内容'.repeat(30) } })
  expect(response.ok()).toBe(true)
  await open(page, '/admin/media')
  await page.getByTestId('media-alt').fill('审查媒体'.repeat(20))
  await page.getByTestId('media-file').setInputFiles({ name: 'layout.png', mimeType: 'image/png', buffer: png })
  await expect(page.locator('.admin-media-asset')).not.toHaveCount(0)
  const draft = await (await page.request.post('/api/v1/admin/articles', { headers, data: { title: '隔离回收站长标题'.repeat(15), slug: 'ops-layout-trash', content: '隔离正文' } })).json()
  expect((await page.request.delete(`/api/v1/admin/articles/${draft.id}`, { headers })).ok()).toBe(true)
  for (const path of ['profile', 'taxonomy', 'media', 'content', 'assistant']) {
    await open(page, `/admin/${path}`)
    await expect(page.locator(path === 'assistant' ? '.assistant-management' : '.resource-ops').first()).toBeVisible()
    if (path === 'assistant') await expect(page.locator('.am-availability')).toBeVisible()
    for (const theme of ['light', 'dark']) {
      await page.setViewportSize({ width: 1440, height: 900 })
      if (await page.locator('html').evaluate(el => el.classList.contains('dark')) !== (theme === 'dark')) await page.getByRole('button', { name: '切换颜色主题' }).click()
      await expect(page.locator('html')).toHaveClass(theme === 'dark' ? /dark/ : /light/)
      await page.evaluate(async () => {
        await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))
      })
      await expect.poll(() => page.evaluate(() => document.getAnimations().filter(animation => animation instanceof CSSTransition && animation.playState === 'running').length)).toBe(0)
      for (const width of [320, 390, 767, 768, 1024, 1440]) {
        await page.setViewportSize({ width, height: width === 320 ? 480 : 900 })
        await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth), { message: `${path}/${theme}/${width}` }).toBeLessThanOrEqual(1)
        if (width === 390) {
          const mobileAxe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
          expect(mobileAxe.violations, `${path}/${theme}/mobile`).toEqual([])
        }
        if ([390, 1440].includes(width)) await page.screenshot({ path: join(info.project.outputDir, `ops-${path}-${theme}-${width}.png`), fullPage: true, animations: 'disabled' })
      }
      const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()
      expect(axe.violations, `${path}/${theme}`).toEqual([])
    }
  }
})

test('ops profile', async ({ page }) => {
  await login(page)
  await open(page, '/admin/profile')
  await page.getByTestId('profile-name').fill('审查名片')
  await fail(page, '**/api/v1/admin/profile', 'PATCH')
  await page.getByTestId('profile-save').click()
  await expect(page.getByRole('alert')).toContainText('保存失败')
  await expect(page.getByTestId('profile-name')).toHaveValue('审查名片')
  await page.unroute('**/api/v1/admin/profile')
  await page.getByTestId('profile-save').click()
  await expect(page.getByText('个人名片已更新')).toBeVisible()
  for (const path of ['/', '/about']) {
    await open(page, path)
    await expect(page.getByTestId('profile-card').getByRole('heading', { name: '审查名片', exact: true })).toBeVisible()
  }
})

test('ops taxonomy', async ({ page }) => {
  const headers = await login(page)
  await open(page, '/admin/taxonomy')
  const tags = page.getByTestId('taxonomy-tags')
  await tags.getByTestId('tags-name').fill('隔离标签')
  await tags.getByTestId('tags-slug').fill('ops-tag')
  await fail(page, '**/api/v1/admin/tags', 'POST')
  await tags.getByTestId('tags-submit').click()
  await expect(tags.getByRole('alert')).toContainText('保存失败')
  await expect(tags.getByTestId('tags-name')).toHaveValue('隔离标签')
  await page.unroute('**/api/v1/admin/tags')
  await tags.getByTestId('tags-submit').click()
  const tagRow = tags.locator('article').filter({ hasText: 'ops-tag' })
  await expect(tagRow).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await tagRow.getByRole('button', { name: '删除' }).click()
  await expect(tagRow).toHaveCount(0)
  const section = page.getByTestId('taxonomy-categories')
  await section.getByTestId('categories-name').fill('审查新栏目')
  await section.getByTestId('categories-slug').fill('ops-category')
  await section.getByTestId('categories-submit').click()
  const row = section.locator('article').filter({ hasText: 'ops-category' })
  await expect(row).toBeVisible()
  await page.setViewportSize({ width: 390, height: 480 })
  await row.getByRole('button', { name: '编辑' }).focus()
  await page.keyboard.press('Enter')
  await expect(section.getByTestId('categories-name')).toBeFocused()
  await section.getByTestId('categories-name').fill('审查更新栏目')
  await section.getByTestId('categories-submit').click()
  await expect(row).toContainText('审查更新栏目')
  const categories = await (await page.request.get('/api/v1/admin/categories')).json()
  const category = categories.find((item: { slug: string }) => item.slug === 'ops-category')
  const created = await page.request.post('/api/v1/admin/articles', { headers, data: { title: '栏目公开验证', slug: 'ops-category-post', content: '隔离正文', category_id: category.id } })
  expect(created.ok()).toBe(true)
  const article = await created.json()
  expect((await page.request.post(`/api/v1/admin/articles/${article.id}/publish`, { headers, data: { version: article.version } })).ok()).toBe(true)
  page.on('dialog', dialog => dialog.accept())
  await row.getByRole('button', { name: '删除' }).click()
  await expect(section.getByRole('alert')).toContainText('无法删除')
  await expect(row).toBeVisible()
  await open(page, '/articles')
  await expect(page.getByRole('link', { name: /审查更新栏目/ })).toBeVisible()
})

test('ops media', async ({ page }) => {
  await login(page)
  await open(page, '/admin/media')
  await page.getByTestId('media-alt').fill('资源闭环')
  await fail(page, '**/api/v1/admin/media', 'POST')
  await page.getByTestId('media-file').setInputFiles({ name: 'ops.png', mimeType: 'image/png', buffer: Buffer.concat([png, Buffer.from('ops-media')]) })
  await expect(page.getByTestId('media-retry-failed')).toBeVisible()
  await page.unroute('**/api/v1/admin/media')
  await page.getByTestId('media-retry-failed').click()
  const asset = page.locator('.admin-media-asset').filter({ hasText: '资源闭环' }).first()
  await expect(asset).toBeVisible()
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }))
  await asset.getByRole('button', { name: '复制 Markdown' }).click()
  await expect(page.getByText('剪贴板不可用，请手动复制下方内容。')).toBeVisible()
  const markdown = await page.getByLabel('可手动选择并复制').inputValue()
  expect(markdown).toContain('![资源闭环]')
  page.on('dialog', dialog => dialog.accept())
  await fail(page, '**/api/v1/admin/media/*/discard', 'POST')
  await asset.getByRole('button', { name: '移除', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('移除失败')
  await expect(asset).toBeVisible()
  await page.unroute('**/api/v1/admin/media/*/discard')
  await asset.getByRole('button', { name: '移除', exact: true }).click()
  await expect(asset).toHaveCount(0)
  await page.getByRole('combobox', { name: '状态', exact: true }).selectOption('removed')
  await page.getByRole('button', { name: '应用筛选' }).click()
  await expect(asset).toBeVisible()
  await fail(page, '**/api/v1/admin/media/*/restore', 'POST')
  await asset.getByRole('button', { name: '恢复' }).click()
  await expect(page.getByRole('alert')).toContainText('恢复失败')
  await page.unroute('**/api/v1/admin/media/*/restore')
  await asset.getByRole('button', { name: '恢复' }).click()
  await expect(asset).toHaveCount(0)
  await page.getByTestId('media-alt').fill('外链记录')
  await page.getByTestId('media-external-url').fill('https://example.com/ops.png')
  await page.getByTestId('media-external-submit').click()
  await expect(page.getByText('外部图片已登记。')).toBeVisible()
  for (const type of ['articles', 'projects', 'books']) {
    await open(page, `/admin/${type}/new`)
    const editor = page.locator('.writing-markdown textarea')
    await editor.fill(markdown)
    await expect(editor).toHaveValue(markdown)
    await page.locator('.writing-markdown').getByTestId('toggle-media-library').click()
    await page.locator('.writing-markdown .admin-media-asset').filter({ hasText: '资源闭环' }).getByRole('button', { name: '插入 Markdown' }).click()
    await expect.poll(async () => (await editor.inputValue()).split('![资源闭环]').length).toBe(3)
  }
})

test('ops content', async ({ page }) => {
  const headers = await login(page)
  await open(page, '/admin/content')
  await fail(page, '**/api/v1/admin/exports/markdown', 'GET')
  await page.getByTestId('export-markdown').click()
  await expect(page.getByText('导出失败，请重试。')).toBeVisible()
  await page.unroute('**/api/v1/admin/exports/markdown')
  const download = page.waitForEvent('download')
  await page.getByTestId('export-markdown').click()
  expect((await download).suggestedFilename()).toBe('gavin-markdown.zip')
  const file = { name: 'ops-import.md', mimeType: 'text/markdown', buffer: Buffer.from('---\n' + JSON.stringify({ type: 'article', title: '隔离导入', slug: 'ops-import' }) + '\n---\n\n仅草稿正文') }
  await fail(page, '**/api/v1/admin/imports/markdown', 'POST')
  await page.getByTestId('import-markdown').setInputFiles(file)
  await expect(page.getByText(/导入失败/)).toBeVisible()
  await page.unroute('**/api/v1/admin/imports/markdown')
  await page.getByTestId('import-markdown').setInputFiles(file)
  await expect(page.getByText('已导入 1 项草稿。')).toBeVisible()
  const link = page.getByRole('link', { name: /ops-import\.md.*编辑草稿/ })
  const edit = (await link.getAttribute('href'))!
  const id = edit.split('/')[3]
  const publicRows = await (await page.request.get('/api/v1/articles')).json()
  expect(JSON.stringify(publicRows)).not.toContain('ops-import')
  await link.click()
  await expect(page.getByTestId('content')).toHaveValue(/仅草稿正文/)
  expect((await page.request.delete(`/api/v1/admin/articles/${id}`, { headers })).ok()).toBe(true)
  await open(page, '/admin/content')
  const row = page.getByRole('article').filter({ hasText: 'ops-import' })
  await fail(page, '**/api/v1/admin/trash/article/*/restore', 'POST')
  await row.getByRole('button', { name: '恢复' }).click()
  await expect(page.getByTestId('trash-error')).toBeVisible()
  await expect(row).toBeVisible()
  await page.unroute('**/api/v1/admin/trash/article/*/restore')
  await row.getByRole('button', { name: '恢复' }).click()
  await expect(row).toHaveCount(0)
  expect((await page.request.delete(`/api/v1/admin/articles/${id}`, { headers })).ok()).toBe(true)
  await page.reload(); await expectHydrated(page)
  page.on('dialog', dialog => dialog.accept())
  await fail(page, '**/api/v1/admin/trash/article/*', 'DELETE')
  await row.getByRole('button', { name: '永久删除' }).click()
  await expect(page.getByTestId('trash-error')).toBeVisible()
  await expect(row).toBeVisible()
  await page.unroute('**/api/v1/admin/trash/article/*')
  await row.getByRole('button', { name: '永久删除' }).click()
  await expect(row).toHaveCount(0)
})

test('ops markdown import accepts CRLF drafts', async ({ page }) => {
  const headers = await login(page)
  await open(page, '/admin/content')
  const slug = `ops-crlf-${Date.now()}`
  const document = `---\n${JSON.stringify({ type: 'article', title: 'CRLF 导入', slug })}\n---\n\n第一行\n第二行\n`
  const file = {
    name: `${slug}.md`,
    mimeType: 'text/markdown',
    buffer: Buffer.from(document.replace(/\n/g, '\r\n'), 'utf-8'),
  }
  await page.getByTestId('import-markdown').setInputFiles(file)
  await expect(page.getByText('已导入 1 项草稿。')).toBeVisible()
  const link = page.getByRole('link', { name: new RegExp(`${slug}\\.md.*编辑草稿`) })
  const id = (await link.getAttribute('href'))!.split('/')[3]

  expect(JSON.stringify(await (await page.request.get('/api/v1/articles')).json())).not.toContain(slug)
  const draft = await (await page.request.get(`/api/v1/admin/articles/${id}`)).json()
  expect(draft.title).toBe('CRLF 导入')
  expect(draft.content).toContain('第一行\n第二行')
  expect(draft.content).not.toContain('\r')
  expect(draft.status).toBe('draft')

  await link.click()
  await expect(page.getByTestId('content')).toHaveValue(/第一行[\s\S]*第二行/)
  expect((await page.request.delete(`/api/v1/admin/articles/${id}`, { headers })).ok()).toBe(true)
})

test('ops duplicate tag slug reports a conflict without a stuck pending state', async ({ page }) => {
  await login(page)
  await open(page, '/admin/taxonomy')
  const tags = page.getByTestId('taxonomy-tags')
  const slug = `ops-dup-${Date.now()}`
  await tags.getByTestId('tags-name').fill('隔离重复标签')
  await tags.getByTestId('tags-slug').fill(slug)
  await tags.getByTestId('tags-submit').click()
  await expect(tags.locator('article').filter({ hasText: slug })).toBeVisible()

  const observed: { status: number, ms: number }[] = []
  for (let attempt = 0; attempt < 5; attempt += 1) {
    await tags.getByTestId('tags-name').fill(`隔离重复标签 ${attempt}`)
    await tags.getByTestId('tags-slug').fill(slug)
    const responsePromise = page.waitForResponse(response =>
      new URL(response.url()).pathname === '/api/v1/admin/tags'
      && response.request().method() === 'POST',
    )
    const startedAt = Date.now()
    await tags.getByTestId('tags-submit').click()
    const response = await responsePromise
    observed.push({ status: response.status(), ms: Date.now() - startedAt })
    await expect(tags.getByRole('alert')).toContainText('保存失败')
    await expect(tags.getByTestId('tags-submit')).toHaveText('新建标签')
  }

  expect(observed).toHaveLength(5)
  expect(observed.map(entry => entry.status)).toEqual([409, 409, 409, 409, 409])
  expect(Math.max(...observed.map(entry => entry.ms))).toBeLessThan(10_000)
})

test('ops assistant', async ({ page }) => {
  await login(page)
  await open(page, '/admin/assistant')
  await expect(page.getByRole('heading', { name: '暂时无法开放' })).toBeVisible()
  await expect(page.getByRole('button', { name: '向访客开放' })).toBeDisabled()
  await page.setViewportSize({ width: 390, height: 480 })
  await expect(page.getByRole('heading', { name: '今日费用' })).toBeVisible()
  await fail(page, '**/api/v1/admin/assistant', 'GET')
  await page.getByRole('button', { name: '刷新状态' }).click()
  await expect(page.getByRole('status').filter({ hasText: '可能已过期' })).toBeVisible()
  await page.unroute('**/api/v1/admin/assistant')
  await page.getByRole('button', { name: '刷新状态' }).click()
  await expect(page.getByText(/上次成功读取于/)).toHaveCount(0)
  await page.getByRole('link', { name: '高级维护' }).click()
  await expect(page.getByRole('heading', { name: '运行诊断' })).toBeVisible()
  const rebuild = page.waitForResponse(r => r.url().endsWith('/admin/assistant/index/rebuilds') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '重建公开知识索引' }).click()
  await page.getByRole('dialog').getByRole('button', { name: '重建公开知识索引' }).click()
  await rebuild
  await expect(page.locator('.assistant-operation').or(page.getByRole('alert')).first()).toBeVisible()
})


test('tx', async ({ page }, info) => {
  test.setTimeout(120_000)
  const headers = await login(page)
  await open(page, '/admin/taxonomy')
  const categories = page.getByTestId('taxonomy-categories')
  await categories.getByTestId('categories-name').fill('阶段五栏目')
  await categories.getByTestId('categories-slug').fill('studio-category')
  await fail(page, '**/api/v1/admin/categories', 'POST')
  await categories.getByTestId('categories-submit').click()
  await expect(categories.getByRole('alert')).toContainText('保存失败')
  await expect(categories.getByTestId('categories-name')).toHaveValue('阶段五栏目')
  await page.unroute('**/api/v1/admin/categories')
  await categories.getByTestId('categories-submit').click()
  const row = categories.locator('article').filter({ hasText: 'studio-category' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(categories.getByTestId('categories-name')).toBeFocused()
  await categories.getByTestId('categories-name').fill('改名栏目')
  await categories.getByTestId('categories-submit').click()
  await expect(row).toContainText('改名栏目')
  const cats = await (await page.request.get('/api/v1/admin/categories')).json()
  const category = cats.find((item: { slug: string }) => item.slug === 'studio-category')
  const article = await page.request.post('/api/v1/admin/articles', { headers, data: { title: '关联文章', slug: 'studio-category-article', content: '正文', category_id: category.id } })
  expect(article.ok()).toBe(true)
  page.on('dialog', dialog => dialog.accept())
  await row.getByRole('button', { name: '删除', exact: true }).click()
  await expect(categories.getByRole('alert')).toContainText('无法删除')
  await expect(row).toBeVisible()
  const tags = page.getByTestId('taxonomy-tags')
  await tags.getByTestId('tags-name').fill('主题标签')
  await tags.getByTestId('tags-slug').fill('studio-tag')
  await tags.getByTestId('tags-submit').click()
  const tag = tags.locator('article').filter({ hasText: 'studio-tag' })
  await expect(tag).toBeVisible()
  await tag.getByRole('button', { name: '编辑' }).click()
  await tags.getByTestId('tags-name').fill('未保存改名')
  await tags.getByRole('button', { name: '取消编辑' }).click()
  await expect(tag).toContainText('主题标签')
  for (const dark of [false, true]) {
    await page.setViewportSize({ width: 1440, height: 1000 })
    if (await page.locator('html').evaluate(el => el.classList.contains('dark')) !== dark) await page.getByRole('button', { name: '切换颜色主题' }).filter({ visible: true }).click()
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
      if ([1440, 390].includes(width)) {
        await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
        await page.screenshot({ path: join(info.project.outputDir, `tx${dark ? 'd' : 'l'}${width}.png`), fullPage: true })
      }
    }
  }
  await tag.getByRole('button', { name: '删除' }).click()
  await expect(tag).toHaveCount(0)
})


test('md', async ({ page }, info) => {
  test.setTimeout(240_000)
  const headers = await login(page)
  await page.route('https://example.com/**', route => route.fulfill({ status: 200, contentType: 'image/png', body: png }))
  for (let i = 0; i < 14; i++) expect((await page.request.post('/api/v1/admin/media/external', { headers, data: { url: `https://example.com/page-${i}.png`, alt_text: `分页素材 ${i}` } })).ok()).toBe(true)
  await open(page, '/admin/media')
  await page.getByTestId('media-alt').fill('上传素材')
  await fail(page, '**/api/v1/admin/media', 'POST')
  await page.getByTestId('media-file').setInputFiles({ name: 'studio.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAADCAIAAAA2iEnWAAAAFElEQVR4nGMUj5vOwMDAxAAGUAoAE7gBEkQlLO8AAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByTestId('media-retry-failed')).toBeVisible()
  await page.unroute('**/api/v1/admin/media')
  await page.getByTestId('media-retry-failed').click()
  await expect(page.getByText('已上传 1 张图片。')).toBeVisible()
  const type = page.getByRole('combobox', { name: '素材类型' })
  const apply = page.getByRole('button', { name: '应用筛选' })
  await page.getByRole('searchbox').fill('分页素材')
  await type.selectOption('external'); await apply.click()
  await expect(page.locator('.admin-media-asset')).toHaveCount(12)
  await type.selectOption('upload')
  const more = page.waitForRequest(r => r.url().includes('/admin/media?') && r.url().includes('offset=12'))
  await page.getByRole('button', { name: '加载更多', exact: true }).click()
  expect(new URL((await more).url()).searchParams.get('source')).toBe('external')
  await expect(page.locator('.admin-media-asset')).toHaveCount(14)
  await page.getByRole('searchbox').fill('上传素材')
  await apply.click(); await expect(page.locator('.admin-media-asset')).toHaveCount(1)
  await expect(page.locator('.admin-media-asset')).toContainText('上传素材')
  await fail(page, '**/api/v1/admin/media?**', 'GET')
  await apply.click()
  await expect(page.getByRole('alert')).toContainText('媒体读取失败')
  await expect(page.locator('.admin-media-asset')).toHaveCount(0)
  await page.unroute('**/api/v1/admin/media?**')
  await page.getByRole('button', { name: '重新读取媒体' }).click()
  const uploaded = page.locator('.admin-media-asset').filter({ hasText: '上传素材' })
  await expect(uploaded).toBeVisible()
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }))
  await uploaded.getByRole('button', { name: '复制 Markdown' }).click()
  await expect(page.getByLabel('可手动选择并复制')).toHaveValue(/上传素材/)
  page.on('dialog', dialog => dialog.accept())
  await uploaded.getByRole('button', { name: '移除', exact: true }).click()
  await expect(uploaded).toHaveCount(0)
  await page.getByRole('combobox', { name: '状态', exact: true }).selectOption('removed'); await apply.click()
  await expect(uploaded).toBeVisible()
  await uploaded.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(uploaded).toHaveCount(0)
  await type.selectOption('external')
  await page.getByRole('combobox', { name: '状态', exact: true }).selectOption('active')
  await page.getByRole('searchbox').fill('分页素材 13'); await apply.click()
  await expect(page.locator('.admin-media-asset')).toHaveCount(1)
  await page.getByRole('searchbox').fill(''); await apply.click()
  await expect(page.locator('.admin-media-asset')).toHaveCount(12)
  await page.locator('.admin-media-asset input[type="checkbox"]').nth(0).check()
  await page.locator('.admin-media-asset input[type="checkbox"]').nth(1).check()
  await page.route('**/api/v1/admin/media/discard-batch', async route => {
    const body = route.request().postDataJSON()
    const response = await route.fetch({ postData: JSON.stringify({ asset_ids: [...body.asset_ids, 999999] }) })
    await route.fulfill({ response })
  })
  await page.getByRole('button', { name: '批量移除' }).click()
  await expect(page.getByRole('alert')).toContainText('1 项未能移除')
  await page.unroute('**/api/v1/admin/media/discard-batch')
  for (const dark of [false, true]) {
    await page.setViewportSize({ width: 1440, height: 1000 })
    if (await page.locator('html').evaluate(el => el.classList.contains('dark')) !== dark) await page.getByRole('button', { name: '切换颜色主题' }).filter({ visible: true }).click()
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
      if ([1440, 390].includes(width)) {
        await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
        await page.screenshot({ path: join(info.project.outputDir, `md${dark ? 'd' : 'l'}${width}.png`) })
      }
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  for (const kind of ['articles', 'books', 'projects']) {
    await open(page, `/admin/${kind}/new`)
    const editor = page.locator('.writing-markdown')
    await editor.locator('textarea').first().fill('保留正文')
    await editor.getByTestId('toggle-media-library').click()
    await editor.getByRole('combobox', { name: '来源' }).selectOption('upload')
    await editor.getByRole('button', { name: '应用筛选' }).click()
    await editor.locator('.admin-media-asset').filter({ hasText: '上传素材' }).getByRole('button', { name: '插入 Markdown' }).click()
    await expect(editor.locator('textarea').first()).toHaveValue(/保留正文/)
    await expect(editor.locator('textarea').first()).toHaveValue(/!\[上传素材\]/)
  }
  await open(page, '/admin/profile')
  await page.getByText('选择或上传头像', { exact: true }).click()
  await page.getByTestId('toggle-media-library').click()
  await page.getByRole('combobox', { name: '来源' }).selectOption('upload')
  await page.getByRole('button', { name: '应用筛选' }).click()
  await page.locator('.admin-media-asset').filter({ hasText: '上传素材' }).getByRole('button', { name: '使用 URL' }).click()
  await expect(page.getByTestId('profile-avatar-url')).toHaveValue(/media/)
})


test('ct', async ({ page }, info) => {
  test.setTimeout(120_000)
  const headers = await login(page)
  await open(page, '/admin/content')
  await fail(page, '**/api/v1/admin/exports/markdown', 'GET')
  await page.getByTestId('export-markdown').click()
  await expect(page.getByText('导出失败，请重试。')).toBeVisible()
  await page.unroute('**/api/v1/admin/exports/markdown')
  const downloading = page.waitForEvent('download')
  await page.getByTestId('export-markdown').click()
  const download = await downloading
  expect(download.suggestedFilename()).toBe('gavin-markdown.zip')
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(Buffer.concat(chunks).subarray(0, 2).toString()).toBe('PK')
  const file = { name: 'studio-import.md', mimeType: 'text/markdown', buffer: Buffer.from('---\n' + JSON.stringify({ type: 'article', title: '迁移长标题'.repeat(10), slug: 'studio-import' }) + '\n---\n\n只创建草稿的正文') }
  await fail(page, '**/api/v1/admin/imports/markdown', 'POST')
  await page.getByTestId('import-markdown').setInputFiles(file)
  await expect(page.getByText(/导入失败/)).toBeVisible()
  await page.unroute('**/api/v1/admin/imports/markdown')
  await page.getByTestId('import-markdown').setInputFiles(file)
  await expect(page.getByText('已导入 1 项草稿。')).toBeVisible()
  const link = page.getByRole('link', { name: /studio-import.md.*编辑草稿/ })
  const id = (await link.getAttribute('href'))!.split('/')[3]
  expect(JSON.stringify(await (await page.request.get('/api/v1/articles')).json())).not.toContain('studio-import')
  await link.click()
  await expect(page.getByTestId('content')).toHaveValue(/只创建草稿的正文/)
  expect((await page.request.delete(`/api/v1/admin/articles/${id}`, { headers })).ok()).toBe(true)
  await open(page, '/admin/content')
  const row = page.getByRole('article').filter({ hasText: 'studio-import' })
  await fail(page, '**/api/v1/admin/trash/article/*/restore', 'POST')
  await row.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.getByTestId('trash-error')).toBeVisible()
  await expect(row).toBeVisible()
  await page.unroute('**/api/v1/admin/trash/article/*/restore')
  await row.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(row).toHaveCount(0)
  expect((await page.request.delete(`/api/v1/admin/articles/${id}`, { headers })).ok()).toBe(true)
  await page.reload(); await expectHydrated(page)
  page.once('dialog', dialog => dialog.dismiss())
  await row.getByRole('button', { name: '永久删除' }).click()
  await expect(row).toBeVisible()
  for (const dark of [false, true]) {
    await page.setViewportSize({ width: 1440, height: 1000 })
    if (await page.locator('html').evaluate(el => el.classList.contains('dark')) !== dark) await page.getByRole('button', { name: '切换颜色主题' }).filter({ visible: true }).click()
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
      if ([1440, 390].includes(width)) {
        await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
        await page.screenshot({ path: join(info.project.outputDir, `ct${dark ? 'd' : 'l'}${width}.png`), fullPage: true })
      }
    }
  }
  page.on('dialog', dialog => dialog.accept())
  await fail(page, '**/api/v1/admin/trash/article/*', 'DELETE')
  await row.getByRole('button', { name: '永久删除' }).click()
  await expect(page.getByTestId('trash-error')).toBeVisible()
  await expect(row).toBeVisible()
  await page.unroute('**/api/v1/admin/trash/article/*')
  await row.getByRole('button', { name: '永久删除' }).click()
  await expect(row).toHaveCount(0)
})
