from __future__ import annotations

from pathlib import Path
from typing import Any

from .config import harness_root, load_config
from .metadata import (
    FrontMatterError,
    markdown_files,
    parse_front_matter,
    values_as_list,
)

GENERATED = "<!-- Generated by python -m tools.harness index. Do not edit. -->"


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _scope_rows(
    scope_root: Path,
    *,
    include_statuses: set[str] | None = None,
    exclude_statuses: set[str] | None = None,
) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in markdown_files(scope_root):
        try:
            metadata, _ = parse_front_matter(path)
        except FrontMatterError:
            continue
        status = str(metadata.get("status", "—"))
        if include_statuses is not None and status not in include_statuses:
            continue
        if exclude_statuses is not None and status in exclude_statuses:
            continue
        rows.append(
            {
                "id": str(metadata.get("id", "")),
                "level": str(metadata.get("level", "")),
                "summary": str(metadata.get("summary", "")),
                "load_when": ", ".join(values_as_list(metadata.get("load_when"))),
                "author": str(metadata.get("author", "—")),
                "status": status,
                "path": path.relative_to(scope_root).as_posix(),
            }
        )
    return sorted(rows, key=lambda item: (item["level"], item["id"], item["path"]))


def render_scope(
    title: str,
    scope_root: Path,
    *,
    include_status: bool = False,
    include_statuses: set[str] | None = None,
    exclude_statuses: set[str] | None = None,
) -> str:
    rows = _scope_rows(
        scope_root,
        include_statuses=include_statuses,
        exclude_statuses=exclude_statuses,
    )
    lines = [
        GENERATED,
        "",
        f"# {title}",
        "",
        "Read this index first. Load only entries whose `load_when` matches the task.",
        "",
    ]
    if include_status:
        active = sum(
            row["path"].startswith("active/") and row["status"] == "active"
            for row in rows
        )
        frozen = sum(
            row["path"].startswith("active/") and row["status"] == "frozen"
            for row in rows
        )
        lines.extend(
            [
                f"Open specifications: **{active} active**, **{frozen} frozen**.",
                "",
                "| ID | Status | Level | Summary | Load when | Author | Path |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
    else:
        lines.extend(
            [
                "| ID | Level | Summary | Load when | Author | Path |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
    for row in rows:
        link = f"[{_cell(row['path'])}]({_cell(row['path'])})"
        if include_status:
            lines.append(
                "| {id} | {status} | {level} | {summary} | {load_when} | {author} | {link} |".format(
                    id=_cell(row["id"]),
                    status=_cell(row["status"]),
                    level=_cell(row["level"]),
                    summary=_cell(row["summary"]),
                    load_when=_cell(row["load_when"]),
                    author=_cell(row["author"]),
                    link=link,
                )
            )
        else:
            lines.append(
                "| {id} | {level} | {summary} | {load_when} | {author} | {link} |".format(
                    id=_cell(row["id"]),
                    level=_cell(row["level"]),
                    summary=_cell(row["summary"]),
                    load_when=_cell(row["load_when"]),
                    author=_cell(row["author"]),
                    link=link,
                )
            )
    if not rows:
        if include_status:
            lines.append("| — | — | — | No indexed documents yet. | — | — | — |")
        else:
            lines.append("| — | — | No indexed documents yet. | — | — | — |")
    return "\n".join(lines) + "\n"


def render_root(config: dict[str, Any]) -> str:
    lines = [
        GENERATED,
        "",
        "# Harness Index",
        "",
        "This is the L1 routing surface for the control plane. Open an area index before loading source documents.",
        "",
        "| Area | Summary | Load when | Index |",
        "| --- | --- | --- | --- |",
    ]
    for area, item in config["indexes"].items():
        path = str(item["path"])
        load_when = ", ".join(str(value) for value in item["load_when"])
        lines.append(
            f"| {_cell(area)} | {_cell(item['summary'])} | {_cell(load_when)} | "
            f"[{_cell(path)}/INDEX.md]({_cell(path)}/INDEX.md) |"
        )
    return "\n".join(lines) + "\n"


def expected_indexes() -> dict[Path, str]:
    config = load_config()
    root = harness_root()
    expected = {root / "INDEX.md": render_root(config)}
    for area, item in config["indexes"].items():
        scope_root = root / str(item["path"])
        expected[scope_root / "INDEX.md"] = render_scope(
            str(item["title"]),
            scope_root,
            include_status=area == "specs",
            include_statuses={str(value) for value in item.get("include_statuses", [])}
            or None,
            exclude_statuses={str(value) for value in item.get("exclude_statuses", [])}
            or None,
        )
    for item in config.get("nested_indexes", {}).values():
        scope_root = root / str(item["path"])
        expected[scope_root / "INDEX.md"] = render_scope(str(item["title"]), scope_root)
    return expected


def write_indexes() -> list[Path]:
    written: list[Path] = []
    for path, content in expected_indexes().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written
